import fs from 'node:fs';

const token = process.env.GITHUB_TOKEN;
const repository = process.env.GITHUB_REPOSITORY;
const eventPath = process.env.GITHUB_EVENT_PATH;

if (!token || !repository || !eventPath) {
  throw new Error('Missing one or more required environment variables: GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_EVENT_PATH.');
}

const event = JSON.parse(fs.readFileSync(eventPath, 'utf8'));
const prNumber = event?.pull_request?.number;
if (!prNumber) {
  throw new Error('pull_request number is missing in event payload.');
}

const findings = JSON.parse(fs.readFileSync('reports/all.json', 'utf8'));
const entries = Array.isArray(findings) ? findings : [];

const counts = entries.reduce(
  (acc, finding) => {
    const severity = typeof finding?.severity === 'string' ? finding.severity.toLowerCase() : 'low';
    if (Object.hasOwn(acc, severity)) {
      acc[severity] += 1;
    }
    return acc;
  },
  { critical: 0, high: 0, medium: 0, low: 0 }
);

const body = [
  '## 🤖 AI Review Summary',
  '',
  '| Severity | Count |',
  '|---|---:|',
  `| critical | ${counts.critical} |`,
  `| high | ${counts.high} |`,
  `| medium | ${counts.medium} |`,
  `| low | ${counts.low} |`,
  '',
  `Total findings: **${entries.length}**.`,
  '',
  '_Generated by AI PR Review System._'
].join('\n');

const [owner, repo] = repository.split('/');
const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`, {
  method: 'POST',
  headers: {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28'
  },
  body: JSON.stringify({ body })
});

if (!response.ok) {
  const message = await response.text();
  throw new Error(`Failed to post summary (${response.status}): ${message}`);
}

console.log('Posted summary comment.');
