apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - secrets/external-secrets.yaml
  - data/postgres-ha.yaml
  - data/redpanda.yaml
  - apps/model-service.yaml
  - autoscale/model-service-hpa.yaml
  - autoscale/worker-keda.yaml
  - ingress/api-ingress.yaml
  - mesh/mtls-strict.yaml
  - observability/prometheus-additional-scrape.yaml
