apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - base/namespace.yaml
  - config/configmap.yaml
  - deployments/analytics.yaml
  - deployments/click-tracker.yaml
  - deployments/admin-panel.yaml
  - deployments/postgres.yaml
  - deployments/jwt-auth.yaml
  - deployments/gpu-renderer.yaml
  - services/analytics.yaml
  - services/click-tracker.yaml
  - services/jwt-auth.yaml
  - kafka/kafka.yaml
  - monitoring/prometheus.yaml
  - mesh/service-mesh.yaml
  - mesh/rate-limit.yaml
  - security/jwt-auth-secret.yaml
  - autoscale/analytics-hpa.yaml
  - autoscale/gpu-renderer-hpa.yaml
  - autoscale/gpu-renderer-keda.yaml
  - autoscale/model-service-hpa.yaml
  - autoscale/model-service-keda.yaml
  - ingress/ingress.yaml
