apiVersion: v1
kind: Service
metadata:
  name: jwt-auth
  namespace: platform
  labels:
    app: jwt-auth
spec:
  selector:
    app: jwt-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
