services:
  prometheus:
    image: prom/prometheus:latest
    container_name: zlttbots-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: zlttbots-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: zlttbots-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: zlttbots-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always

volumes:
  grafana-data:
