apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zlttbots-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: zlttbots-secret-store
  target:
    name: zlttbots-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: zlttbots/platform
        property: DATABASE_URL
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: zlttbots/platform
        property: REDIS_PASSWORD
    - secretKey: STRIPE_KEY
      remoteRef:
        key: zlttbots/platform
        property: STRIPE_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: zlttbots/platform
        property: STRIPE_WEBHOOK_SECRET
    - secretKey: JWT_SECRET
      remoteRef:
        key: zlttbots/platform
        property: JWT_SECRET
