import os
import re

from github import Github
from github.GithubException import GithubException


def _require_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"{name} is required")
    return value


def create_pr(repo_name: str, branch: str, patch: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repo_name):
        raise ValueError("repo_name must match owner/repo")
    if not re.fullmatch(r"[A-Za-z0-9_./-]+", branch):
        raise ValueError("branch has invalid characters")
    if not patch.strip():
        raise ValueError("patch content cannot be empty")

    token = _require_env("GITHUB_TOKEN")
    client = Github(token)
    repo = client.get_repo(repo_name)

    new_branch = f"auto-fix-{branch}"
    base = repo.get_branch(branch)

    try:
        repo.create_git_ref(ref=f"refs/heads/{new_branch}", sha=base.commit.sha)
    except GithubException as exc:
        if exc.status != 422:
            raise

    repo.create_file(
        path="AUTO_FIX.patch",
        message="chore(security): add generated auto-fix patch",
        content=patch,
        branch=new_branch,
    )

    pull = repo.create_pull(
        title="🤖 Auto Security Fix",
        body="Generated by AI fix engine. Please review before merge.",
        head=new_branch,
        base=branch,
    )
    return pull.html_url
