# path: infrastructure/scripts/zttato-resource-optimizer.sh
#!/usr/bin/env bash
#
# zTTato Platform Resource Optimizer
# - Detect CPU / RAM / Disk
# - Generate tuned configs for Docker, Postgres, Redis
# - Recommend worker counts
# - Create swap if missing
#
# Usage:
#   bash infrastructure/scripts/zttato-resource-optimizer.sh

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

echo "======================================"
echo "zTTato Platform Resource Optimizer"
echo "======================================"

############################################
# Detect hardware
############################################

CPU_CORES=$(nproc)
RAM_MB=$(free -m | awk '/Mem:/ {print $2}')
DISK_GB=$(df -BG / | awk 'NR==2 {gsub("G","",$2); print $2}')

echo "Detected system:"
echo "CPU cores : $CPU_CORES"
echo "RAM       : ${RAM_MB}MB"
echo "Disk      : ${DISK_GB}GB"

############################################
# Calculate tuning
############################################

POSTGRES_SHARED_BUFFERS=$((RAM_MB / 4))
POSTGRES_WORK_MEM=$((RAM_MB / 64))
REDIS_MAXMEM=$((RAM_MB / 8))
WORKERS=$((CPU_CORES * 2))

echo ""
echo "Recommended configuration:"
echo "Postgres shared_buffers : ${POSTGRES_SHARED_BUFFERS}MB"
echo "Postgres work_mem       : ${POSTGRES_WORK_MEM}MB"
echo "Redis maxmemory         : ${REDIS_MAXMEM}MB"
echo "Worker processes        : ${WORKERS}"

############################################
# Generate Postgres config
############################################

PGCONF="$ROOT/infrastructure/postgres/postgresql.auto.conf"

cat > "$PGCONF" <<EOF
# Auto-generated by zTTato Resource Optimizer

shared_buffers = ${POSTGRES_SHARED_BUFFERS}MB
work_mem = ${POSTGRES_WORK_MEM}MB
maintenance_work_mem = 512MB
effective_cache_size = $((RAM_MB / 2))MB
max_connections = 200
EOF

echo "Postgres config written -> $PGCONF"

############################################
# Generate Redis config
############################################

REDISCONF="$ROOT/infrastructure/redis.conf"

cat > "$REDISCONF" <<EOF
# Auto-generated Redis tuning

maxmemory ${REDIS_MAXMEM}mb
maxmemory-policy allkeys-lru
appendonly yes
EOF

echo "Redis config written -> $REDISCONF"

############################################
# Docker daemon tuning
############################################

DOCKERCONF="/etc/docker/daemon.json"

sudo mkdir -p /etc/docker

sudo tee "$DOCKERCONF" >/dev/null <<EOF
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "50m",
    "max-file": "3"
  },
  "default-ulimits": {
    "nofile": {
      "Name": "nofile",
      "Hard": 64000,
      "Soft": 64000
    }
  }
}
EOF

echo "Docker daemon tuned -> $DOCKERCONF"

############################################
# Swap setup
############################################

SWAP_EXIST=$(swapon --show | wc -l)

if [ "$SWAP_EXIST" -eq 0 ]; then
  echo ""
  echo "Creating 8GB swap..."

  sudo fallocate -l 8G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile

  echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab

  echo "Swap enabled"
fi

############################################
# Worker configuration
############################################

WORKERCONF="$ROOT/infrastructure/start/workers.auto.conf"

cat > "$WORKERCONF" <<EOF
# Worker configuration

UPLOAD_WORKERS=$((WORKERS / 2))
CRAWLER_WORKERS=$WORKERS
ANALYTICS_WORKERS=$((CPU_CORES))
VIDEO_WORKERS=$((CPU_CORES / 2))
EOF

echo "Worker config -> $WORKERCONF"

############################################
# Restart docker if needed
############################################

echo ""
echo "Restarting Docker..."

sudo systemctl restart docker

echo ""
echo "======================================"
echo "Optimization completed"
echo "======================================"
echo ""
echo "Recommended worker layout:"
cat "$WORKERCONF"
echo ""


# Optional: show system summary
echo "System status:"
echo "--------------------------------"
nproc
free -h
df -h /
echo "--------------------------------"
