apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-arbitrage-engine
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zlttbots
    app.kubernetes.io/component: arbitrage-engine
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: zlttbots
    app.kubernetes.io/component: arbitrage-engine
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
