apiVersion: v1
kind: Namespace
metadata:
  name: zttato-asia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: zttato-asia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        region: asia
    spec:
      containers:
        - name: orchestrator
          image: zttato/orchestrator:latest
          env:
            - name: REGION
              value: asia
