apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredSecurityControls
metadata:
  name: zlttbots-required-security-controls
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    allowedRepos:
      - zlttbots/
      - postgres
