apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredSecurityControls
metadata:
  name: zttato-required-security-controls
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    allowedRepos:
      - zttato/
      - postgres
